# Change these first
owner: OsintUK
repo: Up-or-Down

sites:

   - name: Nulled
     url: nulled.to
   - name: 
     url: cracked.io
   - name: 
     url: sinister.ly
   - name: 
     url: bhf.im
   - name: 
     url: chitachok.fun 
   - name: 
     url: crackingitaly.to
   - name: 
     url: patched.to
   - name: 
     url: crdclub.su
   - name: 
     url: nohide.space
   - name: 
     url: darknetweb.ru
   - name: 
     url: ccccc.sb
   - name: 
     url: moon.sb
   - name: 
     url: cracking.org
   - name: 
     url: shellix.xyz
   - name: 
     url: cracked.sx 
   - name: 
     url: crackia.com
   - name: 
     url: nulledbb.com 
   - name: 
     url: pastebin 
   - name: 
     url: fssquad.com 
   - name: 
     url: darknet.ug
   - name: 
     url: bitify.com
   - name: 
     url: criminalz.org
   - name: 
     url: lolz.guru
   - name: 
     url: vlmi.ws
   - name: 
     url: opencard.top
   - name: 
     url: xreactor.org
   - name: 
     url: crackingx.com
   - name: 
     url: bdfclub.com
   - name: 
     url: drdark.ru
   - name: 
     url: crackinghits.to
   - name: 
     url: forumteam.top
   - name: 
     url: altenens.is
   - name: 
     url: craxpro.io 
   - name: 
     url: darknet.tw
   - name: 
     url: dark-time.com
   - name: 
     url: cashoutgod.ru
   - name: 
     url: cybernulled.com
   - name: 
     url: gerki.pw
   - name: 
     url: niflheim.top
   - name: 
     url: x-slayer.fun
   - name: 
     url: illegals.online
   - name: 
     url: leetforums.ru
   - name: 
     url: emailpass.xyz
   - name: 
     url: noobscracking.weebly.com
   - name: 
     url: novara.biz
   - name: 
     url: v3rmillion.net
   - name: 
     url: crackingall.com
   - name: 
     url: selkis.online
   - name: 
     url: hackportals.org
   - name: 
     url: crackerteam.com
   - name: 
     url: crimemarket.is
   - name: 
     url: darkhack.org
   - name: 
     url: crackingisland.com
   - name: 
     url: lumix.live
   - name: 
     url: openbullet.shop 
   - name: 
     url: voidforum.com
   - name: 
     url: buycvvdumps.org
   - name: 
     url: cardingleaks.ws
   - name: 
     url: crackermain.com
   - name: 
     url: demonforums.net
   - name: 
     url: hackonology.com
   - name: 
     url: leakforum.org
   - name: 
     url: leakzone.net
   - name: 
     url: learntocrack.com
   - name: 
     url: legitcarder.ru
   - name: 
     url: orvx.pw
   - name: 
     url: shoppy.gg
   - name: 
     url: sinfulsite.com 
   - name: 
     url: anonfiles.com
   - name: 
     url: ascarding.com 
   - name: 
     url: bigbosscarding.com
   - name: 
     url: buydumpscvv.com
   - name: 
     url: buypagescript.com
   - name: 
     url: crackiansleaks.com
   - name: 
     url: crackingpro.com
   - name: 
     url: crewgam.blogspot.com
   - name: 
     url: cybercarders.com
   - name: 
     url: darkpro.net
   - name: 
     url: leech.is
   - name: 
     url: legitcarders.ws
   - name: 
     url: unlistedleaks.su
   - name: 
     url: verifiedcarder.net
   - name: 
     url: accsmarket.com
   - name: 
     url: altenens.is 
   - name: 
     url: b117x.com
   - name: 
     url: bpcforum.ru
   - name: 
     url: crackingforum.to
   - name: 
     url: crackingpro.com 
   - name: 
     url: darknetweb.su
   - name: 
     url: djekxa.ru
   - name: 
     url: leaks.so
   - name: 
     url: leech.is 
   - name: 
     url: pjsins.com
   - name: 
     url: validmarket.io
   - name: 
     url: zhyk.org
   - name: 
     url: fog.ac
   - name: 
     url: trustedsellers.ws 
   - name: 
     url: cardingworld.ru
   - name: 
     url: turkhacks.com
   - name: 
     url: youhack.ru
   - name: 
     url: level23hacktools.com
   - name: 
     url: nullc0de.su
   - name: 
     url: coockie.pro
   - name: 
     url: deepweb.to
   - name: 
     url: hack-life.net
   - name: 
     url: frecombo.com
   - name: 
     url: hard-tm.su
   - name: 
     url: itsobr.com
   - name: 
     url: xakers.mybb.ru
   - name: 
     url: dark2web.xyz
   - name: 
     url: mipped.com
   - name: 
     url: openbullet.store 
   - name: 
     url: combofre.com
   - name: 
     url: combo-list.com
   - name: 
     url: softinfo.org
   - name: 
     url: z2u.com
   - name: 
     url: fsecurity.org
   - name: 
     url: pegasushackteam.com
   - name: 
     url: alphazine.ru
   - name: 
     url: crooks.biz
   - name: 
     url: hellofhackers.com
   - name: 
     url: legitmafia.ws
   - name: 
     url: scyllaforums.com
   - name: 
     url: taktakgenerator.blogspot.com
   - name: 
     url: blackbones.net
   - name: 
     url: carding.cx
   - name: 
     url: carding.store
   - name: 
     url: cardingcc.net
   - name: 
     url: cardingforum.cx
   - name: 
     url: cardinglegendz.com
   - name: 
     url: carding-shop.net
   - name: 
     url: cardingstore.com
   - name: 
     url: cardmafia.cc
   - name: 
     url: cashoutarea.net
   - name: 
     url: comboforum.com
   - name: 
     url: crackingdrift.to
   - name: 
     url: crdforum.cc 
   - name: 
     url: cvvshop.to
   - name: 
     url: dumpsbuy.su
   - name: 
     url: hacxx.ys.tj
   - name: 
     url: ihaxglobal.com
   - name: 
     url: instant-hack.to
   - name: 
     url: playerup.com
   - name: 
     url: shadowcarders.com 
   - name: 
     url: validmarket.io 
   - name: 
     url: 365psd.com 
   - name: 
     url: allpsdtemplates.com
   - name: 
     url: best-hack.net
   - name: 
     url: hovatools.com
   - name: 
     url: carders.biz
   - name: 
     url: carders.mx 
   - name: 
     url: cardingteam.ru
   - name: 
     url: cardvilla.cc
   - name: 
     url: cashoutempire.org
   - name: 
     url: clipart.me 
   - name: 
     url: clubhydra.co
   - name: 
     url: combolist-fre.blogspot.com
   - name: 
     url: crackingshare.com
   - name: 
     url: crackingsoul.com/index.php
   - name: 
     url: crackx.to 
   - name: 
     url: crdpro.cc
   - name: 
     url: crimemarket.is
   - name: 
     url: darkstash.com 
   - name: 
     url: darkwebmafias.com
   - name: 
     url: dfgames.com.br
   - name: 
     url: fakeidpsd.org
   - name: 
     url: faketemplate.ru
   - name: 
     url: freepik.com
   - name: 
     url: freshstuff88.com
   - name: 
     url: gamingforum.to 
   - name: 
     url: hackingfather.com
   - name: 
     url: hakepok.ru
   - name: 
     url: howcc.to
   - name: 
     url: jstash.to
   - name: 
     url: leakbd.com 
   - name: 
     url: mpgh.net 
   - name: 
     url: nulledgg.com
   - name: 
     url: nullnoss.org
   - name: 
     url: eground.pro
   - name: 
     url: psdlife.com
   - name: 
     url: spy.gen.tr
   - name: 
     url: sythe.org
   - name: 
     url: teamworld.us
   - name: 
     url: usam.xyz
   - name: 
     url: verifiedshops.cc
   - name: 
     url: verifpro.net
   - name: 
     url: void.to
   - name: 
     url: leaked.wiki
   - name: 
     url: combolist.top
   - name: 
     url: onlinecombilist.blogsport.com
   - name: 
     url: cweb.ws
   - name: 
     url: ufolabs.ru
   - name: 
     url: disboard.org
   - name: 
     url: infected-zone.com
   - name: Telegago
     url: cse.google.com/cse?&cx=006368593537057042503:efxu7xprihg#gsc.tab=0
   - name:
     url: accountbot.io
   - name:
     url: amauta.cc
   - name:
     url: bigfat.cc
   - name:
     url: bitorder.ru
   - name:
     url: blackhatcarding.is
   - name:
     url: breached.to
   - name:
     url: breached.up
   - name:
     url: briansclub.cards
   - name:
     url: ccbases.ru
   - name:
     url: ccshops.sale
   - name:
     url: chopings.cc
   - name:
     url: cpro.su 
   - name:
     url: cv2.su
   - name:
     url: cvvfullzshop.com
   - name:
     url: cvvstore.cc
   - name:
     url: cybershafarat.com
   - name:
     url: easydeals.cx
   - name:
     url: forum.hashkiller.io 
   - name:
     url: genisis.market
   - name:
     url: hackforums.net/index.php
   - name:
     url: legitdumps.cc
   - name:
     url: luxecc.su
   - name:
     url: pp24.market 
   - name:
     url: realandrare.store
   - name:
     url: robocheck.ru
   - name:
     url: rondastore.vip
   - name:
     url: site:telemetr.io
   - name:
     url: skynetzone.org
   - name:
     url: swipestore.cc
   - name:
     url: t.me/card1ngPlanet
   - name:
     url: t.me/s/cardinggclub- Telegram
   - name:
     url: t.me/s/freshstuff_88
   - name:
     url: telemetr.io
   - name:
     url: thefreshstuff.at
   - name:
     url: thejavasea.com
   - name:
     url: trumps-dumps.net
   - name:
     url: uniblast.com
   - name:
     url: validumps.cc
   - name:
     url: vclub.store
   - name:
     url: vclubshop.ru (down 22/11)
   - name:
     url: voughtcardshop.online
   - name:
     url: yalelodge.cc
   - name:
     url: ziser.ru
     
     
     
     

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  
  baseUrl: /Up-or-Down
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
